# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses', to='zumaInfo.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.CharField(default='Pendiente', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zumaInfo.Cliente')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zumaInfo.Interes')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100, null=True)),
                ('factura', models.CharField(max_length=100, null=True)),
                ('cedula', models.CharField(max_length=100, null=True, unique=True)),
                ('valoracion', models.IntegerField(default=0)),
                ('cantidad_votos', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('intereses', models.ManyToManyField(to='zumaInfo.Interes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zumaInfo.Trabajador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='intereses',
            field=models.ManyToManyField(to='zumaInfo.Interes'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
