# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zumaInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='interes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='trabajador',
            field=models.CharField(max_length=500),
        ),
    ]
