# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zumaInfo', '0002_auto_20170511_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zumaInfo.Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='interes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zumaInfo.Interes'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zumaInfo.Trabajador'),
        ),
    ]
